# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(default='b46efb06cf394cb8abc938de5220900d', editable=False, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
